const KEYS={entries:"driveflow.entries.v3",trips:"driveflow.trips.v3",settings:"driveflow.settings.v3",old:"livraisons.entries.v1"};
const defaultSettings={dailyGoal:25,theme:"system",hideMoney:false};
let settings=loadSettings(),entries=loadEntries(),trips=loadTrips(),selectedDate=todayIso();
function loadSettings(){try{return {...defaultSettings,...JSON.parse(localStorage.getItem(KEYS.settings)||"{}")}}catch{return {...defaultSettings}}}
function saveSettings(){localStorage.setItem(KEYS.settings,JSON.stringify(settings))}
function loadEntries(){const raw=localStorage.getItem(KEYS.entries);if(raw){try{return JSON.parse(raw)}catch{}}const old=localStorage.getItem(KEYS.old);if(old){try{const migrated=JSON.parse(old).map(e=>({...e,startTime:"",endTime:"",odoStart:null,odoEnd:null,note:"",importedDistance:0}));localStorage.setItem(KEYS.entries,JSON.stringify(migrated));return migrated}catch{}}const seed=[{date:"2026-08-10",uber:21,deliveroo:17,startTime:"",endTime:"",odoStart:null,odoEnd:null,note:"",importedDistance:0},{date:"2026-08-11",uber:30,deliveroo:9,startTime:"",endTime:"",odoStart:null,odoEnd:null,note:"",importedDistance:0}];localStorage.setItem(KEYS.entries,JSON.stringify(seed));return seed}
function saveEntries(){localStorage.setItem(KEYS.entries,JSON.stringify(entries))}
function loadTrips(){try{return JSON.parse(localStorage.getItem(KEYS.trips)||"[]")}catch{return[]}}
function saveTrips(){localStorage.setItem(KEYS.trips,JSON.stringify(trips))}
function euro(n){return `${Number(n||0).toLocaleString("fr-FR",{maximumFractionDigits:2})} €`}
function num(v){const n=Number(String(v??"").replace(",","."));return Number.isFinite(n)?n:0}
function todayIso(){return iso(new Date())}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function parseDate(s){const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function startWeek(d){const x=new Date(d),wd=(x.getDay()+6)%7;x.setDate(x.getDate()-wd);x.setHours(0,0,0,0);return x}
function minutesBetween(a,b){if(!a||!b)return 0;const [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number);let m=(bh*60+bm)-(ah*60+am);if(m<0)m+=1440;return m}
function fmtMinutes(m){if(!m)return"—";const h=Math.floor(m/60),mm=Math.round(m%60);return mm?`${h}h ${String(mm).padStart(2,"0")}`:`${h}h`}
function fmtKm(k){return k>0?`${k.toLocaleString("fr-FR",{maximumFractionDigits:1})} km`:"—"}
function entry(date){return entries.find(e=>e.date===date)}
function calc(e){const total=num(e?.uber)+num(e?.deliveroo),saved=Math.min(total,settings.dailyGoal),bonus=Math.max(0,total-settings.dailyGoal);const workMin=minutesBetween(e?.startTime,e?.endTime);const odoDistance=(num(e?.odoEnd)>num(e?.odoStart))?num(e.odoEnd)-num(e.odoStart):0;const distance=odoDistance||num(e?.importedDistance);return{total,saved,bonus,workMin,distance,hourly:workMin?total/(workMin/60):0,perKm:distance?total/distance:0,success:total>=settings.dailyGoal}}
function setEntry(data){const i=entries.findIndex(e=>e.date===data.date);if(i>=0)entries[i]=data;else entries.push(data);entries.sort((a,b)=>a.date.localeCompare(b.date));saveEntries()}
function applyTheme(){document.documentElement.classList.remove("light");const darkSystem=matchMedia("(prefers-color-scheme: dark)").matches;const useLight=settings.theme==="light"||(settings.theme==="system"&&!darkSystem);if(useLight)document.documentElement.classList.add("light");document.getElementById("themeSelect").value=settings.theme}
applyTheme();setTimeout(()=>document.getElementById("splash").classList.add("hide"),650);
function dateContext(date){if(date===todayIso())return"Aujourd’hui";if(date===iso(addDays(parseDate(todayIso()),-1)))return"Hier";if(date===iso(addDays(parseDate(todayIso()),1)))return"Demain";return"Journée"}
function longDate(d){return new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(d)}
document.getElementById("prevDay").onclick=()=>{selectedDate=iso(addDays(parseDate(selectedDate),-1));renderAll()};document.getElementById("nextDay").onclick=()=>{selectedDate=iso(addDays(parseDate(selectedDate),1));renderAll()};document.getElementById("openDatePicker").onclick=()=>{const p=document.getElementById("datePicker");p.value=selectedDate;if(p.showPicker)p.showPicker();else p.click()};document.getElementById("datePicker").onchange=e=>{if(e.target.value){selectedDate=e.target.value;renderAll()}};
function renderToday(){const e=entry(selectedDate),c=calc(e);document.getElementById("dateContext").textContent=dateContext(selectedDate);document.getElementById("dateLabel").textContent=longDate(parseDate(selectedDate));document.getElementById("todayTotal").textContent=euro(c.total);document.getElementById("todayUber").textContent=euro(e?.uber||0);document.getElementById("todayDeliveroo").textContent=euro(e?.deliveroo||0);document.getElementById("goalText").textContent=euro(settings.dailyGoal);document.getElementById("savedText").textContent=`${euro(c.saved)} mis de côté`;document.getElementById("bonusText").textContent=`+${euro(c.bonus)} bonus`;document.getElementById("goalProgress").style.width=`${Math.min(100,settings.dailyGoal?c.total/settings.dailyGoal*100:100)}%`;const b=document.getElementById("goalBadge");b.className="badge ";if(!e){b.classList.add("neutral");b.textContent="À saisir"}else if(c.success){b.classList.add("success");b.textContent="Objectif atteint ✓"}else{b.classList.add("warning");b.textContent=`${euro(settings.dailyGoal-c.total)} à faire`}document.getElementById("workTime").textContent=fmtMinutes(c.workMin);document.getElementById("distanceText").textContent=fmtKm(c.distance);document.getElementById("hourlyText").textContent=c.hourly?`${euro(c.hourly)}/h`:"—";document.getElementById("perKmText").textContent=c.perKm?`${euro(c.perKm)}/km`:"—";applyPrivacy()}
function weekData(ref){const start=startWeek(ref),days=[];let saved=0,earned=0,bonus=0,success=0,workMin=0,distance=0;for(let i=0;i<7;i++){const d=addDays(start,i),e=entry(iso(d)),c=calc(e);days.push({d,e,c});saved+=c.saved;earned+=c.total;bonus+=c.bonus;workMin+=c.workMin;distance+=c.distance;if(c.success)success++}return{start,end:addDays(start,6),days,saved,earned,bonus,success,workMin,distance}}
function renderWeek(){const w=weekData(parseDate(selectedDate)),goal=settings.dailyGoal*7;document.getElementById("weekRange").textContent=`${new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short"}).format(w.start)} – ${new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short"}).format(w.end)}`;document.getElementById("weekSaved").textContent=euro(w.saved);document.getElementById("weekGoalLabel").textContent=`/ ${euro(goal)}`;document.getElementById("weekProgress").style.width=`${Math.min(100,goal?w.saved/goal*100:100)}%`;document.getElementById("weekSuccess").textContent=`${w.success} / 7 jours`;document.getElementById("weekRemaining").textContent=`${euro(Math.max(0,goal-w.saved))} restants`;document.getElementById("weekEarned").textContent=euro(w.earned);document.getElementById("weekBonus").textContent=euro(w.bonus);document.getElementById("weekHours").textContent=fmtMinutes(w.workMin);document.getElementById("weekDistance").textContent=fmtKm(w.distance);const box=document.getElementById("weekBars");box.innerHTML="";const max=Math.max(settings.dailyGoal,...w.days.map(x=>x.c.saved),1);w.days.forEach(x=>{const col=document.createElement("div");col.className="week-col";col.innerHTML=`<div class="week-bar-track"><div class="week-bar" style="height:${Math.min(100,x.c.saved/max*100)}%"></div></div><small>${new Intl.DateTimeFormat("fr-FR",{weekday:"short"}).format(x.d).slice(0,3)}</small>`;col.onclick=()=>{selectedDate=iso(x.d);switchView("today")};box.appendChild(col)});applyPrivacy()}
document.getElementById("thisWeekBtn").onclick=()=>{selectedDate=todayIso();renderAll()};
function filteredEntries(range){const now=parseDate(selectedDate);if(range==="all")return entries;if(range==="week"){const w=weekData(now);return entries.filter(e=>parseDate(e.date)>=w.start&&parseDate(e.date)<=w.end)}const y=now.getFullYear(),m=now.getMonth();return entries.filter(e=>{const d=parseDate(e.date);return d.getFullYear()===y&&d.getMonth()===m})}
function renderStats(){const list=filteredEntries(document.getElementById("statsRange").value);let earned=0,saved=0,bonus=0,days=0,work=0,km=0,uber=0,del=0,best=0;list.forEach(e=>{const c=calc(e);earned+=c.total;saved+=c.saved;bonus+=c.bonus;work+=c.workMin;km+=c.distance;uber+=num(e.uber);del+=num(e.deliveroo);if(c.total>0)days++;best=Math.max(best,c.total)});document.getElementById("statsEarned").textContent=euro(earned);document.getElementById("statsSaved").textContent=euro(saved);document.getElementById("statsBonus").textContent=euro(bonus);document.getElementById("statsDays").textContent=days;document.getElementById("avgDay").textContent=days?euro(earned/days):"—";document.getElementById("avgHour").textContent=work?`${euro(earned/(work/60))}/h`:"—";document.getElementById("bestDay").textContent=best?euro(best):"—";document.getElementById("statsKm").textContent=fmtKm(km);const total=uber+del,pU=total?uber/total*100:0,pD=100-pU;document.getElementById("shareUber").textContent=`${Math.round(pU)} %`;document.getElementById("shareDeliveroo").textContent=total?`${Math.round(pD)} %`:"0 %";document.getElementById("shareUberBar").style.width=`${pU}%`;document.getElementById("shareDelBar").style.width=`${total?pD:0}%`;applyPrivacy()}
document.getElementById("statsRange").onchange=renderStats;
function renderHistory(){const box=document.getElementById("historyList");box.innerHTML="";[...entries].sort((a,b)=>b.date.localeCompare(a.date)).forEach(e=>{const c=calc(e);if(c.total===0&&!c.workMin&&!c.distance)return;const item=document.createElement("div");item.className="history-item";item.innerHTML=`<div><div class="date">${new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"short"}).format(parseDate(e.date))}</div><div class="sub">Uber ${euro(e.uber)} · Deliveroo ${euro(e.deliveroo)}${c.workMin?` · ${fmtMinutes(c.workMin)}`:""}${c.distance?` · ${fmtKm(c.distance)}`:""}</div></div><div class="right"><strong class="money">${euro(c.total)}</strong><small>${euro(c.saved)} épargnés</small></div>`;item.onclick=()=>{selectedDate=e.date;switchView("today")};box.appendChild(item)});if(!box.children.length)box.innerHTML='<div class="card muted">Aucune donnée.</div>';applyPrivacy()}
const sheet=document.getElementById("entrySheet"),backdrop=document.getElementById("entryBackdrop");function openEntry(){const e=entry(selectedDate)||{date:selectedDate,uber:"",deliveroo:"",startTime:"",endTime:"",odoStart:"",odoEnd:"",note:""};document.getElementById("entryTitle").textContent=entry(selectedDate)?"Modifier la journée":"Ajouter la journée";document.getElementById("entryDate").value=e.date;document.getElementById("uberInput").value=e.uber??"";document.getElementById("deliverooInput").value=e.deliveroo??"";document.getElementById("startTime").value=e.startTime||"";document.getElementById("endTime").value=e.endTime||"";document.getElementById("odoStart").value=e.odoStart??"";document.getElementById("odoEnd").value=e.odoEnd??"";document.getElementById("noteInput").value=e.note||"";backdrop.hidden=false;requestAnimationFrame(()=>sheet.classList.add("open"));sheet.setAttribute("aria-hidden","false")}
function closeEntry(){sheet.classList.remove("open");sheet.setAttribute("aria-hidden","true");setTimeout(()=>backdrop.hidden=true,220)}document.getElementById("openEntry").onclick=openEntry;document.getElementById("closeEntry").onclick=closeEntry;backdrop.onclick=closeEntry;document.getElementById("saveEntry").onclick=()=>{const data={date:document.getElementById("entryDate").value,uber:num(document.getElementById("uberInput").value),deliveroo:num(document.getElementById("deliverooInput").value),startTime:document.getElementById("startTime").value,endTime:document.getElementById("endTime").value,odoStart:document.getElementById("odoStart").value===""?null:num(document.getElementById("odoStart").value),odoEnd:document.getElementById("odoEnd").value===""?null:num(document.getElementById("odoEnd").value),note:document.getElementById("noteInput").value.trim(),importedDistance:entry(document.getElementById("entryDate").value)?.importedDistance||0};setEntry(data);selectedDate=data.date;document.getElementById("entryMsg").textContent="Enregistré ✓";renderAll();setTimeout(()=>{document.getElementById("entryMsg").textContent="";closeEntry()},500)};
function switchView(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.getElementById(`${v}View`).classList.add("active");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.getElementById("openEntry").style.display=v==="today"?"block":"none";if(v==="stats")renderStats();if(v==="history")renderHistory();if(v==="week")renderWeek()}
document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function applyPrivacy(){document.querySelectorAll(".money").forEach(el=>el.classList.toggle("hidden-money",settings.hideMoney))}document.getElementById("privacyBtn").onclick=()=>{settings.hideMoney=!settings.hideMoney;saveSettings();applyPrivacy()};document.getElementById("dailyGoalInput").value=settings.dailyGoal;document.getElementById("dailyGoalInput").onchange=e=>{settings.dailyGoal=Math.max(0,num(e.target.value)||25);saveSettings();renderAll()};document.getElementById("themeSelect").onchange=e=>{settings.theme=e.target.value;saveSettings();applyTheme()};matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change",()=>{if(settings.theme==="system")applyTheme()});
function parseCsvLine(line,sep){const out=[];let cur="",q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out}
function parseCSV(text){const lines=text.replace(/\r/g,"").split("\n").filter(x=>x.trim());if(!lines.length)return[];const sep=(lines[0].split(";").length>lines[0].split(",").length)?";":",";const headers=parseCsvLine(lines[0],sep).map(h=>h.trim().toLowerCase());return lines.slice(1).map(line=>{const vals=parseCsvLine(line,sep),o={};headers.forEach((h,i)=>o[h]=(vals[i]??"").trim());return o})}
function normalizeDate(v){v=v.trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""}
function importTrips(rows){let added=0,skipped=0;rows.forEach(r=>{const date=normalizeDate(r.date||""),platform=(r.platform||"").trim(),earn=num(r.earnings);if(!date||!platform||!Number.isFinite(earn)){skipped++;return}const trip={id:`${date}|${r.start_time||""}|${platform}|${r.earnings||""}|${r.origin||""}|${r.destination||""}`.toLowerCase(),date,platform,earnings:earn,start_time:r.start_time||"",end_time:r.end_time||"",duration_minutes:num(r.duration_minutes),distance_km:num(r.distance_km),origin:r.origin||"",destination:r.destination||"",notes:r.notes||""};if(trips.some(t=>t.id===trip.id)){skipped++;return}trips.push(trip);added++});saveTrips();const dates=[...new Set(trips.map(t=>t.date))];dates.forEach(date=>{const dayTrips=trips.filter(t=>t.date===date),existing=entry(date)||{date,uber:0,deliveroo:0,startTime:"",endTime:"",odoStart:null,odoEnd:null,note:"",importedDistance:0};const uber=dayTrips.filter(t=>t.platform.toLowerCase().includes("uber")).reduce((s,t)=>s+t.earnings,0);const deliveroo=dayTrips.filter(t=>t.platform.toLowerCase().includes("deliver")).reduce((s,t)=>s+t.earnings,0);const starts=dayTrips.map(t=>t.start_time).filter(Boolean).sort(),ends=dayTrips.map(t=>t.end_time).filter(Boolean).sort(),dist=dayTrips.reduce((s,t)=>s+t.distance_km,0);setEntry({...existing,uber,deliveroo,startTime:starts[0]||existing.startTime,endTime:ends[ends.length-1]||existing.endTime,importedDistance:dist})});return{added,skipped}}
document.getElementById("chooseCsv").onclick=()=>document.getElementById("csvInput").click();document.getElementById("csvInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;const status=document.getElementById("importStatus");try{const rows=parseCSV(await file.text()),res=importTrips(rows);status.textContent=`Import terminé : ${res.added} course(s) ajoutée(s), ${res.skipped} ignorée(s).`;renderAll()}catch{status.textContent="Impossible de lire ce CSV. Utilise le modèle DriveFlow."}e.target.value=""};
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
document.getElementById("exportJson").onclick=()=>download(`driveflow-backup-${todayIso()}.json`,JSON.stringify({version:3,entries,trips,settings},null,2),"application/json");document.getElementById("restoreJson").onclick=()=>document.getElementById("restoreJsonInput").click();document.getElementById("restoreJsonInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(Array.isArray(d.entries)){entries=d.entries;trips=Array.isArray(d.trips)?d.trips:[];settings={...defaultSettings,...(d.settings||{})};saveEntries();saveTrips();saveSettings();applyTheme();renderAll();alert("Sauvegarde restaurée.")}}catch{alert("Fichier de sauvegarde invalide.")}e.target.value=""};document.getElementById("exportCsv").onclick=()=>{const rows=[["date","uber_eats","deliveroo","total","saved","bonus","start_time","end_time","work_minutes","odometer_start","odometer_end","distance_km","note"]];entries.forEach(e=>{const c=calc(e);rows.push([e.date,e.uber,e.deliveroo,c.total,c.saved,c.bonus,e.startTime||"",e.endTime||"",c.workMin,e.odoStart??"",e.odoEnd??"",c.distance,e.note||""])});const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;download(`driveflow-history-${todayIso()}.csv`,"\ufeff"+rows.map(r=>r.map(esc).join(";")).join("\n"),"text/csv;charset=utf-8")};
function renderAll(){renderToday();renderWeek();renderStats();renderHistory();applyPrivacy()}renderAll();switchView("today");if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("driveflow-sw.js").catch(()=>{}));
